import { MS_PER_DAY, MS_PER_HOUR, MS_PER_MINUTE, type Milestone } from '@/domain/types';

const DAYS = (n: number) => n * MS_PER_DAY;
const YEARS = (n: number) => n * 365.25 * MS_PER_DAY;
const MONTHS = (n: number) => n * 30.44 * MS_PER_DAY;

export const MILESTONES: Milestone[] = [
  {
    id: 'heart-rate',
    title: 'Heart rate drops toward normal',
    body: 'Your pulse begins returning to its normal resting range.',
    offsetMs: 20 * MS_PER_MINUTE,
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'acs',
    phaseId: 'crash',
  },
  {
    id: 'carbon-monoxide',
    title: 'Carbon monoxide clears your blood',
    body: "Blood carbon monoxide returns to a non-smoker’s range, so oxygen moves freely again. CO has a half-life of 4–5 hours, which is why this one takes about a day.",
    offsetMs: 24 * MS_PER_HOUR,
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'acs',
    phaseId: 'crash',
  },
  {
    id: 'nicotine-cleared',
    title: 'Nicotine fully cleared',
    body: 'Nothing left in your bloodstream. Nicotine has a half-life of about 2 hours and its metabolite cotinine about 16–20.',
    offsetMs: DAYS(3),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'co-halflife',
    phaseId: 'crash',
  },
  {
    id: 'withdrawal-peak',
    title: 'The withdrawal peak is behind you',
    body: 'Symptoms usually start within 4–24 hours and peak around day 3. This is the hardest it gets, and it is now behind you.',
    offsetMs: DAYS(3),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'withdrawal-peak',
    phaseId: 'crash',
  },
  {
    id: 'taste-smell',
    title: 'Taste, smell and energy improve',
    body: 'Most people notice food tasting like food again, easier breathing and more energy around this point.',
    offsetMs: DAYS(14),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'taste-smell',
    phaseId: 'fog',
  },
  {
    id: 'craving-adaptation',
    title: 'Craving intensity and receptor adaptation',
    body: 'Smoking increases the density of nicotine receptors in your brain, and abstinence lets that adaptation unwind. There is good evidence the change happens, but no reliable timeline for when it finishes — so this milestone has no date and no progress bar.',
    offsetMs: null,
    offsetEndMs: null,
    slipBehavior: 'qualitative',
    sourceId: 'nachr',
    phaseId: 'consolidation',
  },
  {
    id: 'cough-breathlessness',
    title: 'Coughing and breathlessness decrease',
    body: 'The cilia lining your airways have regrown enough to clear tar, which is also why the cough can get worse before it gets better.',
    offsetMs: MONTHS(1),
    offsetEndMs: MONTHS(12),
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'consolidation',
  },
  {
    id: 'heart-attack-risk',
    title: 'Heart attack risk drops sharply',
    body: 'The single biggest cardiovascular payoff of quitting.',
    offsetMs: YEARS(1),
    offsetEndMs: YEARS(2),
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'long-haul',
  },
  {
    id: 'oral-cancer-stroke',
    title: 'Mouth, throat and larynx cancer risk halves',
    body: 'Stroke risk falls over the same period.',
    offsetMs: YEARS(5),
    offsetEndMs: YEARS(10),
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'long-haul',
  },
  {
    id: 'lung-cancer-halved',
    title: 'Lung cancer risk about half that of a smoker',
    body: 'Bladder, kidney and oesophageal cancer risk fall as well.',
    offsetMs: YEARS(10),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'non-smoker',
  },
  {
    id: 'chd-nonsmoker',
    title: "Coronary heart disease risk close to a non-smoker’s",
    body: 'Fifteen years of sustained abstinence brings your heart disease risk near someone who never smoked.',
    offsetMs: YEARS(15),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'non-smoker',
  },
  {
    id: 'multi-cancer-nonsmoker',
    title: "Several cancer risks close to a non-smoker’s",
    body: 'Mouth, throat, larynx and pancreatic cancer risk approach that of someone who does not smoke.',
    offsetMs: YEARS(20),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'non-smoker',
  },
];
