import { MS_PER_DAY, MS_PER_HOUR, MS_PER_MINUTE, type Milestone } from '@/domain/types';

/*
 * Audiences follow the research recorded in
 * docs/superpowers/specs/2026-09-28-nicotine-products-design.md. Deliberately EXCLUDED:
 *  - carbon-monoxide milestones for heated, vape, snus and pouches (their CO is already at
 *    environmental level — FDA IQOS order, Hartmann-Boyce 2023);
 *  - any dated cancer or heart milestone for non-combustible products without cigarette history
 *    (FDA, WHO and Cochrane all say it is not established);
 *  - lung, cilia and taste recovery for non-combustible products (no data);
 *  - "blood pressure improves" for snus or pouches (af Geijerstam 2025 measured a small rise);
 *  - "gums grow back" (recession is structural); pancreatic-cancer claims for snus either way;
 *  - "X% safer" / "95% less harmful"; "one shisha session equals 100 cigarettes".
 * Roll-your-own shares every cigarette claim: equal CO and carcinogen exposure (ryo-harm).
 */

const DAYS = (n: number) => n * MS_PER_DAY;
const YEARS = (n: number) => n * 365.25 * MS_PER_DAY;
const MONTHS = (n: number) => n * 30.44 * MS_PER_DAY;

export const MILESTONES: Milestone[] = [
  {
    id: 'heart-rate',
    title: 'Heart rate drops toward normal',
    body: 'Your pulse begins returning to its normal resting range.',
    offsetMs: 20 * MS_PER_MINUTE,
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'acs',
    phaseId: 'crash',
    audience: 'smoked',
  },
  {
    id: 'vape-heart-rate',
    title: 'Heart rate drops toward normal',
    body: 'In a controlled study of daily vapers who stopped, heart rate fell during the first days without nicotine. There is no equivalent study for heated tobacco or pouches, so they do not get this milestone.',
    offsetMs: DAYS(1),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'hughes-2020',
    phaseId: 'crash',
    audience: 'vape',
  },
  {
    id: 'carbon-monoxide',
    title: 'Your blood carries its full load of oxygen again',
    body: "Carbon monoxide from smoke takes up room that oxygen should use. About a day after the last cigarette, levels are back in a non-smoker’s range.",
    offsetMs: 24 * MS_PER_HOUR,
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'acs',
    phaseId: 'crash',
    audience: 'smoked',
  },
  {
    id: 'nicotine-cleared',
    title: 'Nicotine fully cleared',
    body: 'Nicotine itself is gone. It has a half-life of about two hours; its breakdown product, cotinine, lasts longer (about 16 hours) and is on its way out.',
    offsetMs: DAYS(3),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'benowitz-2009',
    phaseId: 'crash',
    audience: 'all',
  },
  {
    id: 'withdrawal-peak',
    title: 'The withdrawal peak is behind you',
    body: 'Symptoms usually start within 4–24 hours and hit their high point around day three. From here the curve slopes down. Measured in smokers and vapers; for heated tobacco and pouches it is inferred from how nicotine works.',
    offsetMs: DAYS(3),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'withdrawal-peak',
    phaseId: 'crash',
    audience: 'all',
    overrides: {
      vape: { offsetMs: DAYS(3), offsetEndMs: null, sourceId: 'hughes-2020' },
    },
  },
  {
    id: 'first-week',
    title: 'The first week is usually the roughest for sleep',
    body: 'Waking in the night and restless sleep are recognised withdrawal symptoms. They tend to ease over the next two to four weeks.',
    offsetMs: DAYS(7),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'hughes-2007',
    phaseId: 'fog',
    audience: 'all',
  },
  {
    id: 'oral-heart-rate',
    title: 'Your resting heart rate typically dips this week',
    body: 'People who stopped snus or nicotine pouches had a lower resting pulse after one week. In the same study it drifted back toward its earlier level by week eight, so treat this as a short-term change.',
    offsetMs: DAYS(7),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'af-geijerstam-2025',
    phaseId: 'fog',
    audience: 'oral',
  },
  {
    id: 'two-week-window',
    title: 'Past the highest-risk window',
    body: 'In quit-smoking trials, any use in the first two weeks — especially week two — was a powerful predictor of going back, and most people who relapsed had started in those weeks. Two clean weeks puts that behind you. Measured in smokers; for other products it is inferred.',
    offsetMs: DAYS(14),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'kenford-1994',
    phaseId: 'fog',
    audience: 'all',
  },
  {
    id: 'taste-smell',
    title: 'Taste, smell and energy improve',
    body: 'Many people notice food tasting like food again, easier breathing and more energy by now — for some it starts within the first few days.',
    offsetMs: DAYS(14),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'taste-smell',
    phaseId: 'fog',
    audience: 'smoked',
  },
  {
    id: 'withdrawal-fades',
    title: 'Most withdrawal symptoms have faded',
    body: 'Irritability, restlessness, poor concentration and low mood peak in week one and usually fade over two to four weeks. For some people a few linger longer, and that is still normal.',
    offsetMs: DAYS(14),
    offsetEndMs: DAYS(28),
    slipBehavior: 'restarts',
    sourceId: 'hughes-2007',
    phaseId: 'fog',
    audience: 'all',
  },
  {
    id: 'craving-adaptation',
    title: 'Craving intensity and receptor adaptation',
    body: 'Regular nicotine makes your brain grow extra nicotine receptors, and going without lets that adaptation unwind. One small brain-imaging study found them back at normal levels after six to twelve weeks, but it was too small to put a date on it — so this milestone has no date and no progress bar.',
    offsetMs: null,
    offsetEndMs: null,
    slipBehavior: 'qualitative',
    sourceId: 'nachr',
    phaseId: 'consolidation',
    audience: 'all',
  },
  {
    id: 'cravings-rarer',
    title: 'Cravings usually ease',
    body: 'Somewhere between week four and week six, most people find the urges improve. When one does come, it still passes in three to five minutes.',
    offsetMs: DAYS(28),
    offsetEndMs: DAYS(42),
    slipBehavior: 'restarts',
    sourceId: 'hse-cravings',
    phaseId: 'consolidation',
    audience: 'all',
  },
  {
    id: 'snus-mucosa',
    title: 'The lining where you held snus is healing',
    body: 'The white, wrinkled patch where snus sat usually heals after you stop. In a follow-up study the tissue looked healthy and normal when re-checked three to six months later. Gum recession is a separate issue — mention it to your dentist.',
    offsetMs: MONTHS(3),
    offsetEndMs: null,
    slipBehavior: 'restarts',
    sourceId: 'larsson-1991',
    phaseId: 'consolidation',
    audience: 'snus',
  },
  {
    id: 'mood-lifts',
    title: 'Mood, anxiety and stress tend to be better than if you had kept going',
    body: 'Studies following people for six weeks or more found somewhat less anxiety, depression and stress after quitting than in people who carried on. Measured in people who quit smoking.',
    offsetMs: DAYS(42),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'taylor-2021',
    phaseId: 'consolidation',
    audience: 'all',
  },
  {
    id: 'appetite',
    title: 'Weight change is mostly early',
    body: 'Most of any weight change after quitting happens in the first three months, and it varies widely between people — this is a heads-up, not a forecast. Measured in people who quit smoking.',
    offsetMs: MONTHS(1),
    offsetEndMs: MONTHS(3),
    slipBehavior: 'cumulative',
    sourceId: 'aubin-2012',
    phaseId: 'consolidation',
    audience: 'all',
  },
  {
    id: 'cough-breathlessness',
    title: 'Coughing and breathlessness decrease',
    body: 'It happens gradually over the first year, so it is easier to notice month to month than day to day.',
    offsetMs: MONTHS(1),
    offsetEndMs: MONTHS(12),
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'consolidation',
    audience: 'smoked',
  },
  {
    id: 'long-term-unknown',
    title: 'No published recovery timeline',
    body: 'No health authority has put dates on how risk falls after stopping this product, so this chapter has no dated milestones. What is certain is that stopping ends the ongoing exposure.',
    offsetMs: null,
    offsetEndMs: null,
    slipBehavior: 'qualitative',
    sourceId: 'who-htp-2020',
    phaseId: 'long-haul',
    audience: 'unknown-long-term',
    overrides: {
      vape: { offsetMs: null, offsetEndMs: null, sourceId: 'cochrane-ecig-2025' },
      snus: { offsetMs: null, offsetEndMs: null, sourceId: 'fda-snus-mrtp' },
      pouches: { offsetMs: null, offsetEndMs: null, sourceId: 'fda-zyn-mrtp' },
    },
  },
  {
    id: 'heart-attack-risk',
    title: 'Heart attack risk drops sharply',
    body: 'The drop keeps going after that: by year fifteen, coronary heart disease risk is close to someone who never smoked.',
    offsetMs: YEARS(1),
    offsetEndMs: YEARS(2),
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'long-haul',
    audience: 'smoking-history',
  },
  {
    id: 'oral-cancer-stroke',
    title: 'Mouth, throat and larynx cancer risk halves',
    body: 'Stroke risk falls over the same period.',
    offsetMs: YEARS(5),
    offsetEndMs: YEARS(10),
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'long-haul',
    audience: 'smoking-history',
  },
  {
    id: 'lung-cancer-halved',
    title: 'Lung cancer risk about half that of a smoker',
    body: 'Bladder, kidney and oesophageal cancer risk fall as well.',
    offsetMs: YEARS(10),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'non-smoker',
    audience: 'smoking-history',
  },
  {
    id: 'chd-nonsmoker',
    title: "Coronary heart disease risk close to a non-smoker’s",
    body: 'Fifteen years of sustained abstinence brings your heart disease risk near someone who never smoked.',
    offsetMs: YEARS(15),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'non-smoker',
    audience: 'smoking-history',
  },
  {
    id: 'multi-cancer-nonsmoker',
    title: "Several cancer risks close to a non-smoker’s",
    body: 'Mouth, throat, larynx and pancreatic cancer risk approach that of someone who does not smoke.',
    offsetMs: YEARS(20),
    offsetEndMs: null,
    slipBehavior: 'cumulative',
    sourceId: 'acs',
    phaseId: 'non-smoker',
    audience: 'smoking-history',
  },
];
